import Frequent_words_efficient as fwe

def FindClumps(Text, k, L, t):
    """
    Finds all distinct k-mers that form an (L, t)-clump in Text.
    Returns a space-separated string of matching k-mers.
    """
    patterns = set()
    n = len(Text)
    
    # Slide a window of length L across Text
    for i in range(n - L + 1):
        window = Text[i : i + L]
        
        # Call FrequencyTable directly from your fwe module
        freqMap = fwe.FrequencyTable(window, k)
        
        for pattern, count in freqMap.items():
            if count >= t:
                patterns.add(pattern)
                
    # Return space-separated patterns
    return " ".join(patterns)


# Main execution for testing
if __name__ == "__main__":
    Text = "CGGACTCGACAGATGTGAAGAAATGTGAAGACTGAGTGAAGAGAAGAGGAAACACGACACGACATTGCGACATAATGTACGAATGTAATGTGCCTATGGC"
    k = 5
    L = 75
    t = 4
    Text2="TGTTACCAGTGCAGGGGCTTCGGCCTGGTGCCTTGGCCTCTCTAGTTCGTGTATAACATGCGAATTGCTAACATGCGAAGTAACATGCGAAAATAACATGCGACAATTAACATGCGATTGTAATGCCGAGGTTGGCATGGGGAGCTACGTAAGCTACGTAGGGCTCGAAGAGCTACGTAAATGCCGAGGGCCAGTCCGAATGGAGCTACGTAATAGTGAGCTACGTAGGTACGAGGGTTTCACTTTCAATATATAGGCCGAAGAGCTTGTGCTCCATCTGGGATGTCGGGATGTCCGCAGTATGGATGTCCGCTGTTATGTTGTAGGTTGTAGGGGGATGTCCGCCTTTTAGACCGTATTATGTTGTAGCCAGGTCTGTAGCGTAAAGCAGTGTTTTTGGTGCTCTATTAGCACCCTTAGGCCCCCTTTATCATCGGAGTAACGTTCAGCACCATTGATTCGCCTCTCTTTGCTTCAGTCTTTAGATGAGGATCTCTTTATTGAGGCTGTACACCGATTGAGGCTGGCCGTAGACTTAGTTAGTCCATTATTGAGGCTGGAGGCTGATAGTCCATTGAGGCTGAGGCTGAGGTAGTCCTAGTCCTCCCGGCCGAGTGCAAATAGATTTCATCCGTAAGGGGTTTGCATGTAAGTAAGATTCGTATAATTCAGCATGGTACGGGCCGCCTACTCCACCGACACTATTGCAACCCTTTTATCCTATGGACAGTGACGCGTAAACTTTAATGGTGTGACGCGTACGTACCTTGCACGTTACCCACGTGACGCGTACGCGAGGTGACGCGTACTTGGCGGTGACGCGTACGAGCGGCGATCTTATTCGCGATCTTATATAGATGCTATAATTACTATAAAATAATGGTAGATCTAAAAAGAATTGTTTGCAAGGTGTTTTGTTTGCAAGCGCGTTGTAGTATCTCTGTTTGCAAGTCCGTTTTGGGTTGTTTCGCGTTTTGGGTCCGTTTTGGGTAGCCTTCGTTTTGGGTGGAGCAGGAGGGCGCATATACGCGTTTTGGGTCTCCCTTTAGGTGCGCCAAGGGTGCGCCAAGAGGCCAAGGCGTGCGCCAAGTAGAGGCCGTGCGCCAAGAAGCATCACCCGCGAAACCCGCGCTGCGCATGTACCCGCAGATACCGGATCCCATGAGGGTCTCGAGCTACACGATGCTAACGGAAATGGCGATATCAGTTTAACGCACTTGGACCTACCCTCCTTTCCAAACATGAGGCGCGTCCCATGACTCAAACTTTGATTCCTTAGTTCCCATCCCATGACTCGATCCCATGACTCTGGTTCGAGATACTCCTCCCATGACTGTTCCCATGACTCATGCATTCTTGTTAGGCACGAGAAACCTCGCTAGATAGCCCCCTGTGCGCGCTTTGCCTAGTAATCATGATAGCAACCGTGCGAGGTATCTTGTCGCAAGGAATCTTCGTGGTCACATGTCGCCTATAAGTTTCGCCATAATGACATCAGAGGCTTCTGAGGACGCACACCCGGTGCCGCAAAAGCGAGAGTAAACAATAAGGGAACAAAACAATAAGGGGAGAAAGAAACAATAAGGGGAAGGTAGCATTAATACTCTTCCATAAACAATAAGGGTTGAGGTCGACAACGTGAGACTAAGTTCCCACAGCCAACTATACGGTACAGGAACTTTCACAATGCGAGTCCAGCAGGCACAGGAACTTTATTAAAGAGGTTGTGGGAACAGGAACTTTTTTTACACGTACCCGTATGGTGGTCGCTCCATCATCGATAATGGTACAGATATTCTCGATCTGCTGCGAATTGCGAATTTTTTGAATTGCGAATTTTTTTTATTCGAGGCGTCGTAAGTCCTTGCGAATTTTCGAATTTTTTACGCGCGCGGAATCAGGTTTTCGAACCTGAGCCAGGTATATGCTGTCTAACTCCAAACTTGTCAGAGAATCTGGTAGACGGCACCGCCGCGATGGTTCGGCGGAGCAATAGAATA"
    k2= 10
    L2=100
    t2=4
    clumps = FindClumps(Text, k, L, t)
    print("Distinct k-mers forming (L, t)-clumps:")
    print(clumps)
    print("\nTesting with second text:")
    clumps2 = FindClumps(Text2, k2, L2, t2)
    print("Distinct k-mers forming (L, t)-clumps:")
    print(clumps2)