# Frequent_words_efficient.py

def FrequencyTable(Text, k):
    """Builds a frequency dictionary of all k-mers in Text."""
    freqMap = {}
    n = len(Text)
    for i in range(n - k + 1):
        Pattern = Text[i : i + k]
        if Pattern not in freqMap:
            freqMap[Pattern] = 1
        else:
            freqMap[Pattern] += 1
    return freqMap


def maxMap(dictionary):
    """Returns the maximum count in the frequency dictionary."""
    return max(dictionary.values()) if dictionary else 0


def freqMapToString(freqMap):
    """Converts a frequency map into a space-separated k:v string."""
    return " ".join(f"{k}:{v}" for k, v in freqMap.items())


def BetterFrequentWords(Text, k):
    """Finds the most frequent k-mers in Text."""
    FrequentPatterns = []
    freqMap = FrequencyTable(Text, k)
    maxCount = maxMap(freqMap)

    for Pattern, count in freqMap.items():
        if count == maxCount:
            FrequentPatterns.append(Pattern)

    return " ".join(FrequentPatterns)


# --- Standalone Test Execution ---
if __name__ == "__main__":
    Text = "ATGCCCACTTGGCGTTGTCCTTAGACTTGGTTATGCCCACTTGGCGTCTTGGCGTTGTCCTTAGATGCCCAACTTGGTTCTTGGCGTATGCCCACTTGGCGTTGTCCTTAGCTTGGCGTCTTGGCGTGCTGAACCACTTGGTTACTTGGTTACTTGGTTACTTGGTTTGTCCTTAGATGCCCAACTTGGTTGCTGAACCTGTCCTTAGGCTGAACCATGCCCAATGCCCACTTGGCGTACTTGGTTACTTGGTTGCTGAACCTGTCCTTAGCTTGGCGTGCTGAACCGCTGAACCTGTCCTTAGATGCCCAACTTGGTTTGTCCTTAGGCTGAACCTGTCCTTAGATGCCCAGCTGAACCACTTGGTTATGCCCAACTTGGTTGCTGAACCCTTGGCGTGCTGAACCTGTCCTTAGACTTGGTTGCTGAACCATGCCCAGCTGAACCTGTCCTTAGGCTGAACCCTTGGCGTCTTGGCGTTGTCCTTAGTGTCCTTAGACTTGGTTACTTGGTTATGCCCAACTTGGTTATGCCCATGTCCTTAGATGCCCAATGCCCAACTTGGTTATGCCCACTTGGCGTGCTGAACCGCTGAACCATGCCCACTTGGCGTTGTCCTTAGGCTGAACCACTTGGTTATGCCCAACTTGGTTGCTGAACCACTTGGTTTGTCCTTAGACTTGGTTGCTGAACCACTTGGTTGCTGAACCCTTGGCGTGCTGAACCACTTGGTTTGTCCTTAGCTTGGCGTACTTGGTTATGCCCAACTTGGTTCTTGGCGTATGCCCATGTCCTTAGTGTCCTTAGCTTGGCGTCTTGGCGTATGCCCATGTCCTTAGATGCCCATGTCCTTAGATGCCCACTTGGCGTCTTGGCGT"
    k = 11

    Text2 = "AATTCGTGCCGCACCCAGGAGTAGGGCAGGTCGGGGAAGGTCGGGGACGCACCCAGGCGCACCCAGGCGCACCCAGGGGGTGTTCTTAGGTCGGGGACGCACCCAGGAATTCGTGCAATTCGTGCAGTAGGGCAGTAGGGCAGGTCGGGGAGGGTGTTCTTCGCACCCAGGAGGTCGGGGACGCACCCAGGAGTAGGGCGGGTGTTCTTAATTCGTGCCGCACCCAGGCGCACCCAGGCGCACCCAGGAATTCGTGCCGCACCCAGGCGCACCCAGGAGTAGGGCAGTAGGGCAGGTCGGGGAAATTCGTGCCGCACCCAGGGGGTGTTCTTGGGTGTTCTTCGCACCCAGGAGGTCGGGGAAGTAGGGCAGGTCGGGGACGCACCCAGGAGGTCGGGGAGGGTGTTCTTGGGTGTTCTTAGGTCGGGGAAATTCGTGCAGGTCGGGGAAGGTCGGGGAAGTAGGGCAGTAGGGCAGTAGGGCAATTCGTGCCGCACCCAGGAATTCGTGCAGGTCGGGGAAGTAGGGCAATTCGTGCAGTAGGGCAATTCGTGCAGTAGGGCCGCACCCAGGCGCACCCAGGCGCACCCAGGAGTAGGGCCGCACCCAGGAGTAGGGCAATTCGTGCAGGTCGGGGACGCACCCAGGCGCACCCAGGAGTAGGGCAGTAGGGCGGGTGTTCTTCGCACCCAGGAGGTCGGGGAAATTCGTGCGGGTGTTCTTCGCACCCAGGAGGTCGGGGAGGGTGTTCTTCGCACCCAGGCGCACCCAGGAGTAGGGCAGTAGGGCAGTAGGGCGGGTGTTCTTAGGTCGGGGACGCACCCAGGCGCACCCAGGAGGTCGGGGAGGGTGTTCTTAGTAGGGCAGGTCGGGGAAGGTCGGGGAAATTCGTGCCGCACCCAGGAGTAGGGCAGTAGGGC"
    k2 = 12

    result = BetterFrequentWords(Text, k)
    result2 = BetterFrequentWords(Text2, k2)

    print("Result 1:", result)
    print("\nResult 2:", result2)